# Usa a imagem oficial do .NET SDK 8
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copia os arquivos de projeto (.csproj) primeiro para melhorar o cache do Docker
COPY src/TechChallenge4.Api/*.csproj src/TechChallenge4.Api/
COPY src/TechChallenge4.Domain/*.csproj src/TechChallenge4.Domain/
COPY src/TechChallenge4.Infra/*.csproj src/TechChallenge4.Infra/
COPY tests/TechChallenge4.TestsIntegrado/*.csproj tests/TechChallenge4.TestsIntegrado/

# Restaura os pacotes NuGet
RUN dotnet restore tests/TechChallenge4.TestsIntegrado/TechChallenge4.TestsIntegrado.csproj

# Copia todo o restante do código
COPY src/TechChallenge4.Api/ src/TechChallenge4.Api/
COPY src/TechChallenge4.Domain/ src/TechChallenge4.Domain/
COPY src/TechChallenge4.Infra/ src/TechChallenge4.Infra/
COPY tests/TechChallenge4.TestsIntegrado/ tests/TechChallenge4.TestsIntegrado/

# Compila o projeto de testes
RUN dotnet build tests/TechChallenge4.TestsIntegrado/TechChallenge4.TestsIntegrado.csproj --configuration Release --no-restore

# Executa os testes
CMD ["dotnet", "test", "tests/TechChallenge4.TestsIntegrado/TechChallenge4.TestsIntegrado.csproj", "--logger", "trx;LogFileName=test_results.trx"]
